name: Automatic Testing for Notes Management Web App

on:
  push:
    branches:
      - main # Trigger workflow on push to main branch

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code from GitHub Repo
      uses: actions/checkout@v3

    - name: Setup Node.js in Ubuntu
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Setup Node.js dependencies cache
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies based on package.json
      run: npm install

    - name: Run backend tests
      run: npm run backend-test
